prep builds on netlify + bit of sls offline dev

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -1,13 +1,61 @@
 #!/usr/bin/env bash
 
-if [ ! -d '.venv' ]; then
-    if which virtualenv >/dev/null 2>&1; then
-        echo '' > /dev/null
-    else
-        pip3 install virtualenv
-    fi
+_error=false
+if python3 -m pip --version >/dev/null 2>&1; then
+    echo 'Found pip3'
+else
+    echo "Error: 'python3 -m pip' must be available on path"
+    _error=true
+fi
+if python3 -m virtualenv --version >/dev/null 2>&1; then 
+    echo 'Found virtualenv'
+else
+    echo "Error: 'python3 -m virtualenv' must work"
+    echo "try 'pip3 install virtualenv' or 'sudo apt install python3-virtualenv'"
+    _error=true
+fi
+if which npm >/dev/null 2>&1; then 
+    echo 'Found npm'
+else
+    echo "Error: npm must be available on path"
+    echo "Please install Node v8 or higher"
+    _error=true
+fi
+if tmux -V >/dev/null 2>&1; then 
+    echo 'Found tmux'
+else
+    echo "Error: tmux must be available"
+    echo "Try 'sudo apt install tmux' or 'brew install tmux'"
+    _error=true
+fi
 
-    virtualenv .venv
+
+if $_error; then 
+    exit 1
+fi
+
+
+if [ ! -e 'packages/api/sls-custom.yml' ]; then 
+    cp packages/api/sls-custom.yml.default packages/api/sls-custom.yml
+    echo 'Please edit packages/api/sls-custom.yml if you intend to do any API work.'
+fi
+
+
+if [ ! -e "$HOME/.aws/credentials" ]; then 
+    mkdir -p ~/.aws
+    cat <<EOF >> ~/.aws/credentials
+[default]
+aws_secret_access_key = 1234
+aws_access_key_id = 5678
+EOF
+    echo "⚠ NOTE: I've added a default ~/.aws/credentials file for you"
+fi
+
+
+if [ ! -d '.venv' ]; then
+    echo "Creating virtualenv"
+    python3 -m virtualenv .venv
+    echo "Created virtualenv in .venv"
 fi
 
 source .venv/bin/activate
